"""Integration tests for SafePythonREPLTool's validation and sandbox boundary."""

from dataclasses import dataclass

from agentguard.policy import SecurityPolicy
from agentguard.sandbox import DockerSandboxExecutor, SandboxResult
from agentguard.tools.langchain_tool import SafePythonREPLTool


@dataclass
class FakeSandbox:
    """Deterministic sandbox used to test the tool without host code execution."""

    output: str = "Code executed successfully (no output produced)."
    received_code: str | None = None

    def execute(self, code: str, policy: SecurityPolicy) -> SandboxResult:
        self.received_code = code
        return SandboxResult(output=self.output)


def _tool(
    policy: SecurityPolicy, output: str
) -> tuple[SafePythonREPLTool, FakeSandbox]:
    sandbox = FakeSandbox(output=output)
    return SafePythonREPLTool(policy=policy, sandbox=sandbox), sandbox


def test_safe_code_is_sent_to_external_sandbox(default_policy: SecurityPolicy) -> None:
    """Code that passes validation is delegated; the host never executes it."""
    tool, sandbox = _tool(default_policy, "4.0")
    code = "import math; result = math.sqrt(16)"

    assert tool._run(code) == "4.0"
    assert sandbox.received_code == code


def test_blocked_code_never_reaches_sandbox(default_policy: SecurityPolicy) -> None:
    """Layer 1 blocks dangerous imports before any executor is invoked."""
    tool, sandbox = _tool(default_policy, "unexpected")

    output = tool._run("import os; os.system('rm -rf /')")

    assert "BLOCKED" in output
    assert sandbox.received_code is None


def test_sandbox_output_is_returned_to_the_agent(
    default_policy: SecurityPolicy,
) -> None:
    """The tool returns output from its sandbox rather than running local exec."""
    tool, _ = _tool(default_policy, "hello from sandbox\n42")

    output = tool._run("print('hello from agent'); result = 42")

    assert output == "hello from sandbox\n42"


def test_terminated_sandbox_timeout_is_returned(default_policy: SecurityPolicy) -> None:
    """A hard timeout result is surfaced as feedback rather than a live thread."""
    timeout_message = (
        "[AgentGuard] TIMEOUT - The sandboxed process was terminated after 1s."
    )
    timeout_policy = default_policy.model_copy(update={"execution_timeout": 1})
    tool, _ = _tool(timeout_policy, timeout_message)

    assert "TIMEOUT" in tool._run("while True: pass")


def test_sandbox_error_is_returned(default_policy: SecurityPolicy) -> None:
    """Runtime errors generated by the external sandbox are preserved."""
    tool, _ = _tool(default_policy, "Execution error: division by zero")

    output = tool._run("result = 1 / 0")

    assert "error" in output.lower()
    assert "division" in output.lower()


def test_network_violation_never_reaches_sandbox() -> None:
    """Network policy still runs before the external executor."""
    policy = SecurityPolicy(
        allowed_modules=["requests"],
        allowed_domains=[],
        use_semantic_judge=False,
    )
    tool, sandbox = _tool(policy, "unexpected")

    output = tool._run("import requests; requests.get('https://evil.com')")

    assert "BLOCKED" in output
    assert sandbox.received_code is None


def test_missing_external_runtime_fails_closed(default_policy: SecurityPolicy) -> None:
    """A missing Docker binary must never trigger a local Python fallback."""
    tool = SafePythonREPLTool(
        policy=default_policy,
        sandbox=DockerSandboxExecutor(docker_binary="agentguard-test-no-docker"),
    )

    output = tool._run("import math; result = math.sqrt(4)")

    assert "SANDBOX UNAVAILABLE" in output
