"""
Layer 1 — AST Static Validator.

Analyses the Abstract Syntax Tree of LLM-generated code
without executing it, blocking forbidden imports and system calls.
"""

import ast

from agentguard.exceptions import SecurityBlockedError
from agentguard.policy import SecurityPolicy

# Calls that are unconditionally forbidden, regardless of the policy.
_FORBIDDEN_CALLS: set[str] = {
    "exec",
    "eval",
    "compile",
    "__import__",
    "open",
}


class ASTValidator:
    """
    Validates Python source code using static AST analysis.

    This is Layer 1 of the AgentGuard pipeline. It is fast (no I/O,
    no network) and catches the most obvious attack vectors.
    """

    def __init__(self, policy: SecurityPolicy) -> None:
        self._policy = policy

    def validate(self, code: str) -> None:
        """
        Parse and inspect the code AST.

        Args:
            code: Raw Python source code generated by the LLM agent.

        Raises:
            SecurityBlockedError: If the code contains forbidden imports
                or dangerous built-in calls.
            SyntaxError: If the code is not valid Python.
        """
        try:
            tree = ast.parse(code)
        except SyntaxError as exc:
            raise SecurityBlockedError(
                layer="AST Validator",
                reason=f"Invalid Python syntax: {exc}",
                code=code,
            ) from exc

        for node in ast.walk(tree):
            self._check_imports(node, code)
            self._check_calls(node, code)

    def _check_imports(self, node: ast.AST, code: str) -> None:
        """Block any import not explicitly whitelisted in the policy."""
        if isinstance(node, ast.Import):
            for alias in node.names:
                module = alias.name.split(".")[0]
                if module not in self._policy.allowed_modules:
                    raise SecurityBlockedError(
                        layer="AST Validator",
                        reason=f"Forbidden import detected: '{module}'",
                        code=code,
                    )
        elif isinstance(node, ast.ImportFrom):
            module = (node.module or "").split(".")[0]
            if module not in self._policy.allowed_modules:
                raise SecurityBlockedError(
                    layer="AST Validator",
                    reason=f"Forbidden import detected: '{module}'",
                    code=code,
                )

    def _check_calls(self, node: ast.AST, code: str) -> None:
        """Block unconditionally dangerous built-in calls."""
        if isinstance(node, ast.Call):
            func_name: str | None = None
            if isinstance(node.func, ast.Name):
                func_name = node.func.id
            elif isinstance(node.func, ast.Attribute):
                func_name = node.func.attr

            if func_name and func_name in _FORBIDDEN_CALLS:
                raise SecurityBlockedError(
                    layer="AST Validator",
                    reason=f"Forbidden built-in call detected: '{func_name}'",
                    code=code,
                )
