"""
Layer 2 — Network Filter.

Uses regex to detect network calls targeting domains
not explicitly whitelisted in the SecurityPolicy.
"""

import re

from agentguard.exceptions import SecurityBlockedError
from agentguard.policy import SecurityPolicy

# Captures URLs/domains in common patterns like requests.get("https://evil.com")
_URL_PATTERN: re.Pattern[str] = re.compile(
    r"""(?:https?://|requests\.(get|post|put|delete|patch|head)\s*\()\s*['"]([\w.\-/:?=&%]+)['"]""",
    re.IGNORECASE,
)


class NetworkFilter:
    """
    Validates network access in LLM-generated code against the policy whitelist.

    This is Layer 2 of the AgentGuard pipeline. It scans source code as
    plain text using regex patterns to detect outbound network calls.

    Note:
        This layer is heuristic by nature. Sophisticated obfuscation may
        evade it — that is precisely why Layer 3 (semantic judge) exists.
    """

    def __init__(self, policy: SecurityPolicy) -> None:
        self._policy = policy

    def validate(self, code: str) -> None:
        """
        Scan the code for network calls and check domains against the whitelist.

        Args:
            code: Raw Python source code generated by the LLM agent.

        Raises:
            SecurityBlockedError: If a network call targets a non-whitelisted
                domain, or if any network call is detected when the whitelist
                is empty (meaning all network access is forbidden).
        """
        matches = _URL_PATTERN.findall(code)
        if not matches:
            return  # No network calls detected — pass

        # If the whitelist is empty, ALL network access is forbidden
        if not self._policy.allowed_domains:
            raise SecurityBlockedError(
                layer="Network Filter",
                reason="Network access is forbidden by the security policy.",
                code=code,
            )

        for _, url in matches:
            domain = self._extract_domain(url)
            if not any(domain.endswith(allowed) for allowed in self._policy.allowed_domains):
                raise SecurityBlockedError(
                    layer="Network Filter",
                    reason=f"Network call to non-whitelisted domain: '{domain}'",
                    code=code,
                )

    @staticmethod
    def _extract_domain(url: str) -> str:
        """Extract the base domain from a URL string."""
        url = url.split("//")[-1]  # strip scheme
        return url.split("/")[0].split("?")[0]  # strip path & query
